name: gh-pages
on: push

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: Deploy to Pages
        run: ./bin/ghPages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}